"""Árbol de categorías maestro compartido entre IA y carga inicial."""

CATEGORY_TREE = [
    {
        "name": "Cómputo (Hardware)",
        "slug": "computo-hardware",
        "children": [
            {
                "name": "PC Gaming",
                "slug": "pc-gaming",
                "children": [
                    {"name": "Tarjetas Madre Gamer", "slug": "tarjetas-madre-gamer"},
                    {"name": "Tarjetas de Video Gamer", "slug": "tarjetas-video-gamer"},
                    {"name": "Monitores Gamer", "slug": "monitores-gamer"},
                    {"name": "Audífonos Gamer", "slug": "audifonos-gamer-pc-gaming"},
                    {"name": "Mouse Gamer", "slug": "mouse-gamer"},
                    {"name": "Kit Gamer de Teclado y Mouse", "slug": "kit-gamer-teclado-mouse"},
                    {"name": "Mousepad Gamer", "slug": "mousepad-gamer"},
                    {"name": "Gabinetes Gamer", "slug": "gabinetes-gamer"},
                    {"name": "Fuentes de Poder para PC's", "slug": "fuentes-poder-pc-gamer"},
                    {"name": "PC´s Gamer", "slug": "pcs-gamer"},
                    {"name": "Sillas Gamer", "slug": "sillas-gamer"},
                    {"name": "Escritorios Gamer", "slug": "escritorios-gamer"},
                    {"name": "Laptops Gamer", "slug": "laptops-gamer"},
                    {"name": "Sofás Gamer", "slug": "sofas-gamer"},
                    {"name": "Juegos para PC", "slug": "juegos-para-pc"},
                    {"name": "Routers Gamer", "slug": "routers-gamer"},
                    {"name": "Lentes de Realidad Virtual", "slug": "lentes-realidad-virtual"},
                    {"name": "Asientos Simuladores", "slug": "asientos-simuladores"},
                ],
            },
            {
                "name": "Componentes",
                "slug": "componentes",
                "children": [
                    {"name": "Procesadores", "slug": "procesadores"},
                    {"name": "Procesadores para PC", "slug": "procesadores-para-pc"},
                    {"name": "Procesadores para Servidores", "slug": "procesadores-para-servidores"},
                    {"name": "Tarjetas Madre", "slug": "tarjetas-madre"},
                    {"name": "Tarjetas de Video", "slug": "tarjetas-de-video"},
                    {"name": "Gabinetes", "slug": "gabinetes"},
                    {"name": "Fuentes de Poder para PC's", "slug": "fuentes-poder-pc"},
                    {"name": "Enfriamiento y Ventilación", "slug": "enfriamiento-ventilacion"},
                    {"name": "Enfriamiento Líquido", "slug": "enfriamiento-liquido"},
                    {"name": "Ventiladores", "slug": "ventiladores"},
                    {"name": "Disipadores para CPU", "slug": "disipadores-cpu"},
                    {"name": "Disipadores para VGA", "slug": "disipadores-vga"},
                    {"name": "Ventiladores para RAM", "slug": "ventiladores-ram"},
                    {"name": "Control de Ventiladores", "slug": "control-ventiladores"},
                    {"name": "Pasta Térmica", "slug": "pasta-termica"},
                    {"name": "Accesorios para Enfriamiento Líquido", "slug": "accesorios-enfriamiento-liquido"},
                    {"name": "Tarjetas de Expansión", "slug": "tarjetas-expansion"},
                    {"name": "Tarjetas PCI Express", "slug": "tarjetas-pci-express"},
                    {"name": "Tarjetas PCI", "slug": "tarjetas-pci"},
                    {"name": "ExpressCard", "slug": "expresscard"},
                    {"name": "Tarjetas de Sonido", "slug": "tarjetas-sonido"},
                    {"name": "Tarjetas de Televisión", "slug": "tarjetas-television"},
                    {"name": "Tarjetas para Captura de Video", "slug": "tarjetas-captura-video"},
                    {"name": "Accesorios para Gabinetes", "slug": "accesorios-gabinetes"},
                    {"name": "Placas de Desarrollo", "slug": "placas-desarrollo"},
                    {"name": "Sensores para Placas de Desarrollo", "slug": "sensores-placas-desarrollo"},
                    {"name": "Pantallas para Placas de Desarrollo", "slug": "pantallas-placas-desarrollo"},
                    {"name": "Protoboards", "slug": "protoboards"},
                    {"name": "LEDs", "slug": "leds"},
                    {"name": "Módulos y Motores", "slug": "modulos-motores"},
                    {"name": "Cables y Jumpers", "slug": "cables-jumpers"},
                    {"name": "Montajes para Placas de Desarrollo", "slug": "montajes-placas-desarrollo"},
                    {"name": "Transistores", "slug": "transistores"},
                    {"name": "Interruptores para Placas de Desarrollo", "slug": "interruptores-placas-desarrollo"},
                    {"name": "Accesorios para Placas de Desarrollo", "slug": "accesorios-placas-desarrollo"},
                    {"name": "Cámaras para Placas de Desarrollo", "slug": "camaras-placas-desarrollo"},
                ],
            },
            {
                "name": "Discos Duros / SSD / NAS",
                "slug": "discos-ssd-nas",
                "children": [
                    {"name": "SSD", "slug": "ssd"},
                    {"name": "Discos Duros Internos para PC", "slug": "hdd-interno-pc"},
                    {"name": "Discos Duros Internos para Laptop", "slug": "hdd-interno-laptop"},
                    {"name": "Discos Duros para Servidores", "slug": "hdd-servidores"},
                    {"name": "Discos Duros para Videovigilancia", "slug": "hdd-videovigilancia"},
                    {"name": "Discos Duros para NAS", "slug": "hdd-nas"},
                    {"name": "Discos Duros Externos", "slug": "hdd-externos"},
                    {"name": "Almacenamiento NAS", "slug": "almacenamiento-nas"},
                    {"name": "Almacenamiento MSA", "slug": "almacenamiento-msa"},
                    {"name": "Accesorios para Discos Duros", "slug": "accesorios-discos-duros"},
                    {"name": "Gabinetes de Discos Duros", "slug": "gabinetes-discos-duros"},
                    {"name": "Adaptadores de Discos Duros", "slug": "adaptadores-discos-duros"},
                    {"name": "Racks Extraíbles y Backplanes", "slug": "racks-extraibles-backplanes"},
                    {"name": "Soportes y Accesorios para Montaje", "slug": "soportes-accesorios-montaje"},
                    {"name": "Accesorios para SSD", "slug": "accesorios-ssd"},
                    {"name": "Disipadores para SSD", "slug": "disipadores-ssd"},
                    {"name": "Gabinetes para SSD", "slug": "gabinetes-ssd"},
                    {"name": "SSD's para Servidores", "slug": "ssd-servidores"},
                    {"name": "Accesorios para NAS", "slug": "accesorios-nas"},
                    {"name": "SSD's Externos", "slug": "ssd-externos"},
                ],
            },
            {
                "name": "Memorias RAM y Flash",
                "slug": "memorias-ram-flash",
                "children": [
                    {"name": "Memorias RAM para PC", "slug": "ram-pc"},
                    {"name": "Memorias RAM para Laptop", "slug": "ram-laptop"},
                    {"name": "Memorias RAM para Mac", "slug": "ram-mac"},
                    {"name": "Memorias RAM para Servidores", "slug": "ram-servidores"},
                    {"name": "Memorias Flash", "slug": "memorias-flash"},
                    {"name": "Memorias USB", "slug": "memorias-usb"},
                    {"name": "Lectores de Memoria", "slug": "lectores-memoria"},
                    {"name": "Duplicadores de Datos y Soportes", "slug": "duplicadores-datos-soportes"},
                ],
            },
            {
                "name": "Monitores",
                "slug": "monitores",
                "children": [
                    {"name": "Monitores", "slug": "monitores-desktop"},
                    {"name": "Monitores Portátiles", "slug": "monitores-portatiles"},
                    {"name": "Soportes para Monitores", "slug": "soportes-monitores"},
                    {"name": "Filtros de Privacidad para Monitores", "slug": "filtros-privacidad-monitores"},
                    {"name": "Estaciones de Trabajo", "slug": "estaciones-trabajo"},
                    {"name": "Accesorios para Estaciones de Trabajo", "slug": "accesorios-estaciones-trabajo"},
                    {"name": "Bases para Monitores", "slug": "bases-monitores"},
                ],
            },
            {
                "name": "Dispositivos de Entrada",
                "slug": "dispositivos-entrada",
                "children": [
                    {"name": "Kits de Teclado y Mouse", "slug": "kits-teclado-mouse"},
                    {"name": "Mouse", "slug": "mouse"},
                    {"name": "Mousepads", "slug": "mousepads"},
                    {"name": "Teclados", "slug": "teclados"},
                    {"name": "Teclados Numéricos", "slug": "teclados-numericos"},
                    {"name": "Keycaps y Switches", "slug": "keycaps-switches"},
                    {"name": "Tablets Gráficas", "slug": "tablets-graficas"},
                    {"name": "Controles de Juego para PC", "slug": "controles-juego-pc"},
                    {"name": "Volantes para Simulador", "slug": "volantes-simulador"},
                    {"name": "Digitalizadores de Firma", "slug": "digitalizadores-firma"},
                    {"name": "Stream Decks", "slug": "stream-decks"},
                    {"name": "Audífonos Gamer", "slug": "audifonos-gamer-input"},
                ],
            },
            {"name": "Audífonos Gamer", "slug": "audifonos-gamer", "children": []},
            {
                "name": "Redes",
                "slug": "redes",
                "children": [
                    {"name": "Switches", "slug": "switches"},
                    {"name": "Router", "slug": "router"},
                    {"name": "Firewall", "slug": "firewall"},
                    {"name": "Access Points", "slug": "access-points"},
                    {"name": "CPE PtMP y PtP", "slug": "cpe-ptmp-ptp"},
                    {"name": "Wi-Fi en Malla", "slug": "wifi-malla"},
                    {"name": "Extensor de Señal WiFi", "slug": "extensor-senal-wifi"},
                    {"name": "Modems", "slug": "modems"},
                    {"name": "Adaptadores de Red USB", "slug": "adaptadores-red-usb"},
                    {"name": "Powerline", "slug": "powerline"},
                    {"name": "Antenas", "slug": "antenas"},
                    {"name": "Unidades de Red Óptica", "slug": "unidades-red-optica"},
                    {"name": "Backhauls", "slug": "backhauls"},
                    {"name": "Accesorios de Redes", "slug": "accesorios-redes"},
                    {"name": "Controladores Inalámbricos", "slug": "controladores-inalambricos"},
                    {"name": "Módulos Transceptores", "slug": "modulos-transceptores"},
                    {"name": "Tarjetas y Módulos de Red", "slug": "tarjetas-modulos-red"},
                    {"name": "Convertidores de Medios", "slug": "convertidores-medios"},
                    {"name": "Energía para Redes", "slug": "energia-redes"},
                    {"name": "Routerboards", "slug": "routerboards"},
                    {"name": "Multiplexores", "slug": "multiplexores"},
                    {"name": "Montaje de Redes", "slug": "montaje-redes"},
                    {"name": "Servidores Seriales", "slug": "servidores-seriales"},
                    {"name": "Torres y Mástiles", "slug": "torres-mastiles"},
                ],
            },
            {
                "name": "Servidores",
                "slug": "servidores",
                "children": [
                    {"name": "Servidores", "slug": "servidores-equipo"},
                    {"name": "Servidores de Impresión", "slug": "servidores-impresion"},
                    {"name": "Unidades de Cinta", "slug": "unidades-cinta"},
                    {"name": "Discos Duros para Servidores", "slug": "hdd-servidores-serv"},
                    {"name": "Accesorios para Servidores", "slug": "accesorios-servidores"},
                    {"name": "Racks y Gabinetes", "slug": "racks-gabinetes"},
                    {"name": "Charolas para Racks y Gabinetes", "slug": "charolas-racks-gabinetes"},
                    {"name": "Consolas de Rack", "slug": "consolas-rack"},
                    {"name": "Soportes y Paneles", "slug": "soportes-paneles"},
                    {"name": "Fuentes de Poder", "slug": "fuentes-poder-servidores"},
                    {"name": "Cableado Estructurado para Servidores", "slug": "cableado-estructurado-servidores"},
                    {"name": "Kits de Montaje", "slug": "kits-montaje"},
                    {"name": "Switches KVM", "slug": "switches-kvm"},
                    {"name": "Cables KVM", "slug": "cables-kvm"},
                    {"name": "Enfriamiento para Servidores", "slug": "enfriamiento-servidores"},
                    {"name": "Sistemas Operativos para Servidores", "slug": "sistemas-operativos-servidores"},
                    {"name": "Soportes de Datos", "slug": "soportes-datos"},
                    {"name": "DLT", "slug": "dlt"},
                    {"name": "Ultrium", "slug": "ultrium"},
                    {"name": "Cartuchos de Limpieza", "slug": "cartuchos-limpieza"},
                    {"name": "Monitoreo para Servidores", "slug": "monitoreo-servidores"},
                ],
            },
            {
                "name": "Adaptadores",
                "slug": "adaptadores",
                "children": [
                    {"name": "Adaptadores Audio", "slug": "adaptadores-audio"},
                    {"name": "Adaptadores Audio USB", "slug": "adaptadores-audio-usb"},
                    {"name": "Adaptadores Audio AUX", "slug": "adaptadores-audio-aux"},
                    {"name": "Toslink", "slug": "toslink"},
                    {"name": "Adaptadores XLR", "slug": "adaptadores-xlr"},
                    {"name": "Adaptadores Video", "slug": "adaptadores-video"},
                    {"name": "Adaptadores Video DVI", "slug": "adaptadores-video-dvi"},
                    {"name": "Adaptadores Video HDMI", "slug": "adaptadores-video-hdmi"},
                    {"name": "Adaptadores Video VGA / HD15", "slug": "adaptadores-video-vga-hd15"},
                    {"name": "Adaptadores Video DisplayPort", "slug": "adaptadores-video-displayport"},
                    {"name": "Adaptadores Video S-Video", "slug": "adaptadores-video-svideo"},
                    {"name": "Divisores de Video", "slug": "divisores-video"},
                    {"name": "Extensores y Receptores de Video", "slug": "extensores-receptores-video"},
                    {"name": "Puentes SLI", "slug": "puentes-sli"},
                    {"name": "Capturadoras de Video", "slug": "capturadoras-video"},
                    {"name": "Adaptadores PC", "slug": "adaptadores-pc"},
                    {"name": "Switches KVM", "slug": "switches-kvm-adapt"},
                    {"name": "Bluetooth", "slug": "bluetooth"},
                    {"name": "Adaptadores PC USB", "slug": "adaptadores-pc-usb"},
                    {"name": "Adaptadores PC Serial", "slug": "adaptadores-pc-serial"},
                    {"name": "Adaptadores PC Teclado", "slug": "adaptadores-pc-teclado"},
                    {"name": "Adaptadores PC SATA", "slug": "adaptadores-pc-sata"},
                    {"name": "Adaptadores PC PS/2", "slug": "adaptadores-pc-ps2"},
                    {"name": "Adaptadores PC IDE", "slug": "adaptadores-pc-ide"},
                    {"name": "RJ-45", "slug": "rj45"},
                    {"name": "Repetidores USB", "slug": "repetidores-usb"},
                ],
            },
            {
                "name": "Cables",
                "slug": "cables",
                "children": [
                    {"name": "Bobinas", "slug": "bobinas"},
                    {"name": "Bobinas de Cable Ethernet", "slug": "bobinas-cable-ethernet"},
                    {"name": "Bobinas de Cable Coaxial", "slug": "bobinas-cable-coaxial"},
                    {"name": "Bobinas de Fibra Óptica", "slug": "bobinas-fibra-optica"},
                    {"name": "Bobinas de Cable Eléctrico", "slug": "bobinas-cable-electrico"},
                    {"name": "Bobinas de Cable para Alarmas", "slug": "bobinas-cable-alarmas"},
                    {"name": "Bobinas de Cable de Acero", "slug": "bobinas-cable-acero"},
                    {"name": "Cables PC", "slug": "cables-pc"},
                    {"name": "Cables PC KVM", "slug": "cables-pc-kvm"},
                    {"name": "Cables PC USB", "slug": "cables-pc-usb"},
                    {"name": "Cables PC VGA / HD15", "slug": "cables-pc-vga-hd15"},
                    {"name": "Cables PC Serial", "slug": "cables-pc-serial"},
                    {"name": "Cables PC SATA / eSATA", "slug": "cables-pc-sata-esata"},
                    {"name": "Cables PC SAS", "slug": "cables-pc-sas"},
                    {"name": "Cables PC FireWire", "slug": "cables-pc-firewire"},
                    {"name": "Cables de Audio / Video", "slug": "cables-audio-video"},
                    {"name": "Cables de Audio / Video DVI", "slug": "cables-audio-video-dvi"},
                    {"name": "Cables de Audio / Video HDMI", "slug": "cables-audio-video-hdmi"},
                    {"name": "Cables de Audio / Video VGA", "slug": "cables-audio-video-vga"},
                    {"name": "Cables de Audio / Video DisplayPort", "slug": "cables-audio-video-displayport"},
                    {"name": "Cables de Audio / Video AUX", "slug": "cables-audio-video-aux"},
                    {"name": "Cables XLR", "slug": "cables-xlr"},
                    {"name": "Cables de Audio / Video BNC", "slug": "cables-audio-video-bnc"},
                    {"name": "Cables de Audio / Video Toslink", "slug": "cables-audio-video-toslink"},
                    {"name": "Cables de Audio / Video RCA", "slug": "cables-audio-video-rca"},
                    {"name": "Cables de Red", "slug": "cables-red"},
                    {"name": "Cables Patch", "slug": "cables-patch"},
                    {"name": "Cables Fibra Óptica", "slug": "cables-fibra-optica"},
                    {"name": "Cables de Antena", "slug": "cables-antena"},
                    {"name": "Cables SFP+", "slug": "cables-sfp-plus"},
                    {"name": "Cables Stack", "slug": "cables-stack"},
                    {"name": "Cables Coaxiales", "slug": "cables-coaxiales"},
                    {"name": "Divisores Ópticos", "slug": "divisores-opticos"},
                    {"name": "Cables de Energía", "slug": "cables-energia"},
                    {"name": "Cables de Poder (Externo)", "slug": "cables-poder-externo"},
                    {"name": "Cables de Poder (Interno)", "slug": "cables-poder-interno"},
                    {"name": "Cableado Estructurado", "slug": "cableado-estructurado"},
                    {"name": "Condulets", "slug": "condulets"},
                    {"name": "Canaletas y Bandejas Portacables", "slug": "canaletas-bandejas-portacables"},
                    {"name": "Sujetadores de Cables", "slug": "sujetadores-cables"},
                    {"name": "Marcadores para Cables", "slug": "marcadores-cables"},
                    {"name": "Tuberías Eléctricas", "slug": "tuberias-electricas"},
                    {"name": "Cables para Impresoras", "slug": "cables-impresoras-cables"},
                    {"name": "Accesorios para Cables", "slug": "accesorios-cables"},
                    {"name": "Jacks de Red", "slug": "jacks-red"},
                    {"name": "Conectores", "slug": "conectores"},
                    {"name": "Tapas y Cajas", "slug": "tapas-cajas"},
                    {"name": "Herramientas para Cables", "slug": "herramientas-cables"},
                    {"name": "Protectores para Cables", "slug": "protectores-cables"},
                    {"name": "Terminales para Cables", "slug": "terminales-cables"},
                    {"name": "Divisores Ópticos", "slug": "divisores-opticos-extra"},
                ],
            },
            {
                "name": "Unidades de Disco",
                "slug": "unidades-disco",
                "children": [
                    {"name": "Quemadores de DVD", "slug": "quemadores-dvd"},
                    {"name": "Quemadores de Blu-ray", "slug": "quemadores-blu-ray"},
                ],
            },
        ],
    },
    {
        'name': 'Audio y Video',
        'slug': 'audio-y-video',
        'children': [
            {
                'name': 'Audio',
                'slug': 'audio',
                'children': [
                    {'name': 'Bocinas', 'slug': 'bocinas-audio'},
                    {'name': 'Bocinas y Bafles', 'slug': 'bocinas-y-bafles'},
                    {'name': 'Bocinas Portátiles', 'slug': 'bocinas-portatiles'},
                    {'name': 'Bocinas para Computadora', 'slug': 'bocinas-para-computadora'},
                    {'name': 'Barras de Sonido', 'slug': 'barras-de-sonido'},
                    {'name': 'Audífonos', 'slug': 'audifonos-audio'},
                    {'name': 'Audífonos Intrauriculares', 'slug': 'audifonos-intrauriculares'},
                    {'name': 'Estéreos', 'slug': 'esteros'},
                    {'name': 'Reproductores MP3 / MP4', 'slug': 'reproductores-mp3-mp4'},
                    {'name': 'Grabadoras Reporteras', 'slug': 'grabadoras-reporteras'},
                    {'name': 'Radios Despertadores', 'slug': 'radios-despertadores'},
                    {'name': 'Sonido para Centros de Entretenimiento', 'slug': 'sonido-centros-entretenimiento'},
                    {'name': 'Home Theater', 'slug': 'home-theater'},
                    {'name': 'Amplificadores y Receptores AV', 'slug': 'amplificadores-receptores-av'},
                    {'name': 'Bocinas para Sistemas de Audio', 'slug': 'bocinas-sistemas-audio'},
                    {'name': 'Barras de Sonido', 'slug': 'barras-de-sonido-2'},
                    {'name': 'Bafles y Subwoofers Profesionales', 'slug': 'bafles-subwoofers-profesionales'},
                    {'name': 'Soportes', 'slug': 'soportes-audio'},
                    {'name': 'Producción de Audio', 'slug': 'produccion-audio'},
                    {'name': 'Equipo para DJ', 'slug': 'equipo-para-dj'},
                    {'name': 'Interfaces de Audio', 'slug': 'interfaces-audio'},
                    {'name': 'Ecualizadores / Crossover / Amplificadores', 'slug': 'ecualizadores-crossover-amplificadores'},
                    {'name': 'Pedales', 'slug': 'pedales'},
                    {'name': 'Proyectores de Luz', 'slug': 'proyectores-luz'},
                    {'name': 'Amplificadores para Audífonos', 'slug': 'amplificadores-audifonos'},
                    {'name': 'Mezcladoras', 'slug': 'mezcladoras'},
                    {'name': 'Instrumentos Musicales', 'slug': 'instrumentos-musicales'},
                    {'name': 'Teclados Musicales', 'slug': 'teclados-musicales'},
                    {'name': 'Accesorios de Audio', 'slug': 'accesorios-audio'},
                    {'name': 'Discos CD', 'slug': 'discos-cd'},
                    {'name': 'Discos DVD', 'slug': 'discos-dvd'},
                    {'name': 'Discos Blu-Ray', 'slug': 'discos-blu-ray'},
                    {'name': 'Estuches y Cajas', 'slug': 'estuches-cajas'},
                    {'name': 'Micrófonos', 'slug': 'microfonos'},
                    {'name': 'Luces Giratorias', 'slug': 'luces-giratorias'},
                    {'name': 'Bases para Audífonos', 'slug': 'bases-para-audifonos'},
                    {'name': 'Accesorios para Micrófonos', 'slug': 'accesorios-microfonos'},
                    {'name': 'Tornamesas', 'slug': 'tornamesas'}
                ]
            },
            {
                'name': 'Foto y Video',
                'slug': 'foto-y-video',
                'children': [
                    {'name': 'Cámaras Digitales', 'slug': 'camaras-digitales'},
                    {'name': 'Cámaras Reflex', 'slug': 'camaras-reflex'},
                    {'name': 'Cámaras de Video', 'slug': 'camaras-de-video'},
                    {'name': 'Cámaras Deportivas', 'slug': 'camaras-deportivas-fv'},
                    {'name': 'Drones', 'slug': 'drones-foto-video'},
                    {'name': 'Cámaras Analógicas', 'slug': 'camaras-analogicas'},
                    {'name': 'Accesorios Foto y Video', 'slug': 'accesorios-foto-video'},
                    {'name': 'Selfie Sticks', 'slug': 'selfie-sticks'},
                    {'name': 'Marcos Digitales', 'slug': 'marcos-digitales'},
                    {'name': 'Lentes', 'slug': 'lentes-fotografia'},
                    {'name': 'Tripies', 'slug': 'tripies'},
                    {'name': 'Cargadores y Baterías', 'slug': 'cargadores-baterias-foto-video'},
                    {'name': 'Fundas y Estuches', 'slug': 'fundas-estuches-foto-video'},
                    {'name': 'Estabilizadores para Celulares', 'slug': 'estabilizadores-celulares'},
                    {'name': 'Iluminación para Foto y Video', 'slug': 'iluminacion-foto-video'}
                ]
            },
            {
                'name': 'TV y Pantallas',
                'slug': 'tv-y-pantallas',
                'children': [
                    {'name': 'Pantallas', 'slug': 'pantallas'},
                    {'name': 'Pantallas Comerciales', 'slug': 'pantallas-comerciales'},
                    {'name': 'Pantallas Interactivas', 'slug': 'pantallas-interactivas'},
                    {'name': 'Accesorios TV', 'slug': 'accesorios-tv'},
                    {'name': 'Reproductores para Transmisión Multimedia', 'slug': 'reproductores-transmision-multimedia'},
                    {'name': 'Sintonizadores para Pantallas', 'slug': 'sintonizadores-pantallas'},
                    {'name': 'Soportes para Pantallas', 'slug': 'soportes-pantallas'},
                    {'name': 'Marcos Interactivos', 'slug': 'marcos-interactivos'},
                    {'name': 'Antenas para Televisión', 'slug': 'antenas-television'},
                    {'name': 'Videowall', 'slug': 'videowall'},
                    {'name': 'Videowalls', 'slug': 'videowalls'},
                    {'name': 'Soportes para Videowalls', 'slug': 'soportes-videowalls'},
                    {'name': 'Accesorios para Videowall', 'slug': 'accesorios-videowall'},
                    {'name': 'Controladores para Videowalls', 'slug': 'controladores-videowalls'},
                ],
            },
            {
                "name": "Proyección",
                "slug": "proyeccion",
                "children": [
                    {"name": "Proyectores", "slug": "proyectores"},
                    {"name": "Accesorios para Proyectores", "slug": "accesorios-proyectores"},
                    {"name": "Pantallas de Proyección", "slug": "pantallas-proyeccion"},
                    {"name": "Lámparas para Proyectores", "slug": "lamparas-proyectores"},
                    {"name": "Soportes de Proyectores", "slug": "soportes-proyectores"},
                    {"name": "Presentadores", "slug": "presentadores"},
                    {"name": "Adaptadores de Red para Proyectores", "slug": "adaptadores-red-proyectores"},
                    {"name": "Lentes para Proyectores", "slug": "lentes-proyectores"},
                    {"name": "Maletines para Proyectores", "slug": "maletines-proyectores"},
                    {"name": "Pizarrones Interactivos", "slug": "pizarrones-interactivos"},
                ],
            },
            {
                "name": "Consolas y Juegos",
                "slug": "consolas-y-juegos",
                "children": [
                    {"name": "Xbox Series X|S", "slug": "xbox-series-xs"},
                    {"name": "Consolas Xbox Series X|S", "slug": "consolas-xbox-series-xs"},
                    {"name": "Juegos Xbox Series X|S", "slug": "juegos-xbox-series-xs"},
                    {"name": "Accesorios para Xbox Series X|S", "slug": "accesorios-xbox-series-xs"},
                    {"name": "Xbox One", "slug": "xbox-one"},
                    {"name": "Juegos Xbox One", "slug": "juegos-xbox-one"},
                    {"name": "Accesorios Xbox One", "slug": "accesorios-xbox-one"},
                    {"name": "Xbox 360", "slug": "xbox-360"},
                    {"name": "Juegos Xbox 360", "slug": "juegos-xbox-360"},
                    {"name": "PlayStation 5 (PS5)", "slug": "playstation-5"},
                    {"name": "Consolas PlayStation 5", "slug": "consolas-playstation-5"},
                    {"name": "Juegos PlayStation 5", "slug": "juegos-playstation-5"},
                    {"name": "Accesorios PlayStation 5", "slug": "accesorios-playstation-5"},
                    {"name": "Playstation 4 (PS4)", "slug": "playstation-4"},
                    {"name": "Consolas Playstation 4", "slug": "consolas-playstation-4"},
                    {"name": "Accesorios Playstation 4", "slug": "accesorios-playstation-4"},
                    {"name": "Playstation 3 (PS3)", "slug": "playstation-3"},
                    {"name": "Accesorios Playstation 3", "slug": "accesorios-playstation-3"},
                    {"name": "Nintendo Wii", "slug": "nintendo-wii"},
                    {"name": "Complementos para Videojuegos", "slug": "complementos-videojuegos"},
                    {"name": "Nintendo Switch", "slug": "nintendo-switch"},
                    {"name": "Consolas Nintendo Switch", "slug": "consolas-nintendo-switch"},
                    {"name": "Juegos Nintendo Switch", "slug": "juegos-nintendo-switch"},
                    {"name": "Accesorios para Nintendo Switch", "slug": "accesorios-nintendo-switch"},
                    {"name": "Consolas Portátiles", "slug": "consolas-portatiles"},
                    {"name": "Consolas Arcade", "slug": "consolas-arcade"},
                ],
            },
            {
                "name": "Gadgets",
                "slug": "gadgets",
                "children": [
                    {"name": "Drones", "slug": "drones-gadgets"},
                    {"name": "Lentes de Realidad Virtual", "slug": "lentes-realidad-virtual-gadgets"},
                    {"name": "Smartwatch", "slug": "smartwatch"},
                    {"name": "Cámaras Deportivas", "slug": "camaras-deportivas-gadgets"},
                    {"name": "Dash Cam", "slug": "dash-cam"},
                    {"name": "Accesorios para Smartwatch", "slug": "accesorios-smartwatch"},
                    {"name": "Accesorios para Drones", "slug": "accesorios-drones"},
                    {"name": "Rastreadores Inteligentes", "slug": "rastreadores-inteligentes"},
                ],
            },
            {
                "name": "GPS y Auto",
                "slug": "gps-y-auto",
                "children": [
                    {"name": "Estéreos para Autos", "slug": "esteros-para-autos"},
                    {"name": "Autoestéreos", "slug": "autoesteros"},
                    {"name": "Amplificadores", "slug": "amplificadores-auto"},
                    {"name": "Bocinas", "slug": "bocinas-auto"},
                    {"name": "Subwoofers", "slug": "subwoofers-auto"},
                    {"name": "Transmisores FM", "slug": "transmisores-fm"},
                    {"name": "Navegadores GPS", "slug": "navegadores-gps"},
                    {"name": "Antena GPS", "slug": "antena-gps"},
                ],
            },
        ],
    },
    {
        "name": "Computadoras",
        "slug": "computadoras",
        "children": [
            {"name": "PC's de Escritorio", "slug": "pcs-de-escritorio", "children": []},
            {"name": "Laptops", "slug": "laptops", "children": []},
            {
                "name": "Tablets",
                "slug": "tablets",
                "children": [
                    {"name": "Tablets", "slug": "tablets-genericas"},
                    {"name": "Tablets Gráficas", "slug": "tablets-graficas"},
                    {"name": "Cargadores Portátiles", "slug": "cargadores-portatiles-tablets"},
                    {"name": "Lápices para Tablets", "slug": "lapices-para-tablets"},
                    {"name": "Fundas y Skins", "slug": "fundas-skins-tablets"},
                    {"name": "Soportes para Celulares y Tablets", "slug": "soportes-celulares-tablets"},
                ],
            },
            {"name": "All in One", "slug": "all-in-one", "children": []},
            {"name": "Mini PC's", "slug": "mini-pcs", "children": []},
            {"name": "Workstations", "slug": "workstations", "children": []},
            {"name": "Barebones", "slug": "barebones", "children": []},
            {"name": "Thin Clients", "slug": "thin-clients", "children": []},
            {
                "name": "Webcam y Audio",
                "slug": "webcam-y-audio",
                "children": [
                    {"name": "Webcams", "slug": "webcams"},
                    {"name": "Audífonos", "slug": "audifonos"},
                ],
            },
            {
                "name": "Accesorios para PC's",
                "slug": "accesorios-para-pcs",
                "children": [
                    {"name": "Bases para PC's", "slug": "bases-para-pcs"},
                    {"name": "Kits de Herramientas", "slug": "kits-de-herramientas"},
                    {"name": "Limpiadores para Electrónicos", "slug": "limpiadores-para-electronicos"},
                    {"name": "Iluminación para PC", "slug": "iluminacion-para-pc"},
                    {"name": "Candados para PC's", "slug": "candados-para-pcs"},
                    {"name": "Lentes para Computadora", "slug": "lentes-para-computadora"},
                ],
            },
            {
                "name": "Accesorios para Laptops",
                "slug": "accesorios-para-laptops",
                "children": [
                    {"name": "Bases para Laptops", "slug": "bases-para-laptops"},
                    {"name": "Docking Stations", "slug": "docking-stations"},
                    {"name": "Cargadores", "slug": "cargadores-laptops"},
                    {"name": "Baterías", "slug": "baterias-laptops"},
                    {"name": "Mochilas para Laptops", "slug": "mochilas-para-laptops"},
                    {"name": "Maletines", "slug": "maletines-laptops"},
                    {"name": "Fundas y Skins", "slug": "fundas-skins-laptops"},
                    {"name": "Filtros de privacidad", "slug": "filtros-privacidad-laptops"},
                    {"name": "Candados para Laptops", "slug": "candados-para-laptops"},
                    {"name": "Lámparas para Laptop", "slug": "lamparas-para-laptop"},
                ],
            },
            {"name": "Paneles PC", "slug": "paneles-pc", "children": []},
        ],
    },
    {
        "name": "Energía",
        "slug": "energia",
        "children": [
            {
                "name": "Protección Contra Descargas",
                "slug": "proteccion-contra-descargas",
                "children": [
                    {"name": "Reguladores de Voltaje", "slug": "reguladores-de-voltaje"},
                    {"name": "No Break / UPS", "slug": "no-break-ups"},
                    {"name": "No Break UPS", "slug": "no-break-ups-2"},
                    {"name": "Baterías para No Break", "slug": "baterias-para-no-break"},
                    {"name": "Accesorios No Break", "slug": "accesorios-no-break"},
                    {"name": "PDU's", "slug": "pdus"},
                    {"name": "Supresores de Picos", "slug": "supresores-de-picos"},
                    {"name": "Reductores de Voltaje", "slug": "reductores-de-voltaje"},
                    {"name": "Protectores PoE", "slug": "protectores-poe"},
                    {"name": "Protectores Coaxiales", "slug": "protectores-coaxiales"},
                ],
            },
            {
                "name": "Adaptadores, Cargadores y Pilas",
                "slug": "adaptadores-cargadores-pilas",
                "children": [
                    {"name": "Cargadores Portátiles", "slug": "cargadores-portatiles-energia"},
                    {"name": "Cargadores de Dispositivos Móviles", "slug": "cargadores-dispositivos-moviles"},
                    {"name": "Pilas", "slug": "pilas"},
                    {"name": "Cargadores de Pilas", "slug": "cargadores-de-pilas"},
                    {"name": "Adaptadores de Energía Universal", "slug": "adaptadores-energia-universal"},
                    {"name": "Extensiones", "slug": "extensiones"},
                    {"name": "Multicontactos", "slug": "multicontactos"},
                ],
            },
            {
                "name": "Energía Computo",
                "slug": "energia-computo",
                "children": [
                    {"name": "Fuentes de Poder para PC's", "slug": "fuentes-poder-pcs"},
                    {"name": "Baterías para Laptop", "slug": "baterias-para-laptop"},
                    {"name": "Cargadores para Laptop", "slug": "cargadores-para-laptop"},
                ],
            },
            {"name": "Energía Foto y Video", "slug": "energia-foto-video", "children": []},
            {"name": "Energía Impresión y Copiado", "slug": "energia-impresion-copiado", "children": []},
            {
                "name": "Energía para Redes",
                "slug": "energia-para-redes",
                "children": [
                    {"name": "Fuentes de Poder para Switches", "slug": "fuentes-poder-switches"},
                    {"name": "Adaptadores PoE", "slug": "adaptadores-poe"},
                    {"name": "Protectores PoE", "slug": "protectores-poe-redes"},
                ],
            },
            {
                "name": "Energía Seguridad y Vigilancia",
                "slug": "energia-seguridad-vigilancia",
                "children": [
                    {"name": "Energía para Cámaras y Grabadoras", "slug": "energia-camaras-grabadoras"},
                    {"name": "Energía para Sistemas de Alarmas", "slug": "energia-sistemas-alarmas"},
                    {"name": "Energía Control de Acceso", "slug": "energia-control-acceso"},
                    {"name": "Transformadores", "slug": "transformadores"},
                    {"name": "Tarjetas para Fuente de Poder", "slug": "tarjetas-fuente-poder"},
                    {"name": "Estaciones de Descarga", "slug": "estaciones-descarga"},
                ],
            },
            {"name": "Energía Punto de Venta (POS)", "slug": "energia-pos", "children": []},
            {
                "name": "Energía para Telecomunicación",
                "slug": "energia-telecomunicacion",
                "children": [
                    {
                        "name": "Energía para Celulares",
                        "slug": "energia-para-celulares",
                        "children": [
                            {"name": "Cargadores Portátiles", "slug": "cargadores-portatiles-celulares"},
                            {"name": "Kits y Cargadores de Coche", "slug": "kits-cargadores-coche"},
                        ],
                    },
                    {
                        "name": "Energía para Teléfonos Convencionales",
                        "slug": "energia-telefonos-convencionales",
                        "children": [
                            {"name": "Cargadores para Teléfonos Convencionales", "slug": "cargadores-telefonos-convencionales"},
                            {"name": "Bases de Carga", "slug": "bases-carga-telefonos-convencionales"},
                            {"name": "Cables Telefónicos", "slug": "cables-telefonicos"},
                            {"name": "Baterías para Teléfonos Convencionales", "slug": "baterias-telefonos-convencionales"},
                            {"name": "Protectores para Línea Telefónica", "slug": "protectores-linea-telefonica"},
                        ],
                    },
                    {
                        "name": "Energía para Teléfonos VoIP",
                        "slug": "energia-telefonos-voip",
                        "children": [
                            {"name": "Cargadores para Teléfonos VoIP", "slug": "cargadores-telefonos-voip"},
                            {"name": "Bases de Carga", "slug": "bases-carga-telefonos-voip"},
                        ],
                    },
                    {"name": "Energía para Radios", "slug": "energia-radios", "children": []},
                ],
            },
            {
                "name": "Energía para el Hogar",
                "slug": "energia-para-el-hogar",
                "children": [
                    {"name": "Tomacorrientes", "slug": "tomacorrientes"},
                    {"name": "Bases para Medidores", "slug": "bases-para-medidores"},
                    {"name": "Atenuadores", "slug": "atenuadores"},
                    {"name": "Apagadores", "slug": "apagadores"},
                    {"name": "Centros de Carga", "slug": "centros-de-carga"},
                    {"name": "Frentes para Centros de Carga", "slug": "frentes-centros-de-carga"},
                ],
            },
            {
                "name": "Energía para Herramientas Eléctricas",
                "slug": "energia-herramientas-electricas",
                "children": [
                    {"name": "Baterías", "slug": "baterias-herramientas"},
                    {"name": "Baterías Selladas", "slug": "baterias-selladas"},
                    {"name": "Gabinetes para Baterías", "slug": "gabinetes-para-baterias"},
                    {"name": "Cargadores de Baterías Selladas", "slug": "cargadores-baterias-selladas"},
                ],
            },
            {
                "name": "Fuentes Industriales",
                "slug": "fuentes-industriales",
                "children": [
                    {"name": "Fuentes Industriales CD", "slug": "fuentes-industriales-cd"},
                    {"name": "Interruptores Industriales", "slug": "interruptores-industriales"},
                    {"name": "Accesorios para Interruptores", "slug": "accesorios-para-interruptores"},
                    {"name": "Fusibles Industriales y Eléctricos", "slug": "fusibles-industriales-electricos"},
                    {"name": "Disyuntores", "slug": "disyuntores"},
                    {"name": "Tableros de Distribución y Alumbrado", "slug": "tableros-distribucion-alumbrado"},
                    {"name": "Capacitores y Filtros", "slug": "capacitores-filtros"},
                    {"name": "Reactores para Bancos de Capacitores", "slug": "reactores-bancos-capacitores"},
                    {"name": "Gabinetes y Armarios Eléctricos", "slug": "gabinetes-armarios-electricos"},
                    {
                        "name": "Control Industrial",
                        "slug": "control-industrial",
                        "children": [
                            {"name": "Contactores", "slug": "contactores"},
                            {"name": "Arrancadores", "slug": "arrancadores"},
                            {"name": "Relevadores", "slug": "relevadores"},
                            {"name": "Pulsadores", "slug": "pulsadores"},
                            {"name": "Elementos Térmicos", "slug": "elementos-termicos"},
                            {"name": "Luces Piloto", "slug": "luces-piloto"},
                            {"name": "Sensores de Presión", "slug": "sensores-presion"},
                            {"name": "Analizadores de Energía y Potencia", "slug": "analizadores-energia-potencia"},
                        ],
                    },
                ],
            },
            {
                "name": "Estaciones de Carga",
                "slug": "estaciones-de-carga",
                "children": [
                    {"name": "Estación de Carga", "slug": "estacion-de-carga"},
                    {"name": "Estación de Carga Portátil", "slug": "estacion-carga-portatil"},
                    {"name": "Baterías para Estaciones de Carga", "slug": "baterias-estaciones-carga"},
                ],
            },
            {
                "name": "Energía Solar",
                "slug": "energia-solar",
                "children": [
                    {"name": "Paneles Solares", "slug": "paneles-solares"},
                    {"name": "Controladores de Carga Solar", "slug": "controladores-carga-solar"},
                    {"name": "Sistemas de Interconexión a la Red Grid - Tie", "slug": "sistemas-grid-tie"},
                    {"name": "Protección Térmica para Paneles Solares", "slug": "proteccion-termica-paneles-solares"},
                    {"name": "Accesorios para Paneles Solares", "slug": "accesorios-paneles-solares"},
                    {"name": "Cables Fotovoltaicos", "slug": "cables-fotovoltaicos"},
                    {"name": "Módulos de Batería", "slug": "modulos-bateria-solar"},
                    {"name": "Baterías Solares", "slug": "baterias-solares"},
                ],
            },
            {
                "name": "Inversores y Convertidores",
                "slug": "inversores-convertidores",
                "children": [
                    {"name": "Convertidores", "slug": "convertidores"},
                    {"name": "Inversores", "slug": "inversores"},
                    {"name": "Generadores", "slug": "generadores"},
                ],
            },
            {
                "name": "Tierra Física y Pararrayos",
                "slug": "tierra-fisica-pararrayos",
                "children": [
                    {"name": "Tierra Física", "slug": "tierra-fisica"},
                    {"name": "Pararrayos", "slug": "pararrayos"},
                    {"name": "Accesorios para Instalación", "slug": "accesorios-instalacion-tierra-pararrayos"},
                ],
            },
        ],
    },
    {
        "name": "Impresión y Copiado",
        "slug": "impresion-y-copiado",
        "children": [
            {
                "name": "Impresoras y Multifuncionales",
                "slug": "impresoras-y-multifuncionales",
                "children": [
                    {"name": "Impresoras", "slug": "impresoras"},
                    {"name": "Multifuncionales", "slug": "multifuncionales"},
                    {"name": "Plotter", "slug": "plotter"},
                    {"name": "Impresoras Fotográficas", "slug": "impresoras-fotograficas"},
                    {"name": "Impresión y Escaneo 3D", "slug": "impresion-y-escaneo-3d"},
                    {"name": "Impresoras 3D", "slug": "impresoras-3d"},
                    {"name": "Escáners 3D", "slug": "escaners-3d"},
                    {"name": "Bobinas de Filamento", "slug": "bobinas-de-filamento"},
                    {"name": "Resina", "slug": "resina"},
                    {"name": "Accesorios para Impresión 3D", "slug": "accesorios-impresion-3d"},
                    {"name": "Grabadoras Láser", "slug": "grabadoras-laser"},
                    {"name": "Impresoras de Credenciales", "slug": "impresoras-de-credenciales"},
                    {"name": "Impresoras de Etiquetas", "slug": "impresoras-de-etiquetas"},
                    {"name": "Impresoras de Tickets", "slug": "impresoras-de-tickets"},
                    {"name": "Impresoras de Cheques", "slug": "impresoras-de-cheques"},
                    {"name": "Impresoras Móviles", "slug": "impresoras-moviles"},
                    {"name": "Rotuladores", "slug": "rotuladores"},
                ],
            },
            {
                "name": "Escáneres",
                "slug": "escaneres",
                "children": [
                    {"name": "Escáneres", "slug": "escaneres-planos"},
                ],
            },
            {
                "name": "Consumibles para Impresoras",
                "slug": "consumibles-impresoras",
                "children": [
                    {"name": "Tóner", "slug": "toner"},
                    {"name": "Cintas", "slug": "cintas"},
                    {"name": "Cintas para Etiquetadoras", "slug": "cintas-etiquetadoras"},
                    {"name": "Cintas para Impresoras de Tarjetas", "slug": "cintas-impresoras-tarjetas"},
                    {"name": "Cintas de Transferencia Térmica", "slug": "cintas-transferencia-termica"},
                    {"name": "Cartuchos", "slug": "cartuchos"},
                    {"name": "Tintas Sólidas", "slug": "tintas-solidas"},
                    {"name": "Tanques de tinta", "slug": "tanques-de-tinta"},
                    {"name": "Cabezales", "slug": "cabezales"},
                    {"name": "Unidades de Imagen", "slug": "unidades-de-imagen"},
                    {"name": "Fotoconductores", "slug": "fotoconductores"},
                    {"name": "Bobinas de Filamento", "slug": "bobinas-de-filamento-consumibles"},
                    {"name": "Resina", "slug": "resina-consumibles"},
                    {"name": "Bolsas de Tinta", "slug": "bolsas-de-tinta"},
                ],
            },
            {
                "name": "Papeles para Impresoras",
                "slug": "papeles-impresoras",
                "children": [
                    {"name": "Papel", "slug": "papel"},
                    {"name": "Papel Stock", "slug": "papel-stock"},
                    {"name": "Papel Opalina", "slug": "papel-opalina"},
                    {"name": "Papel de Colores", "slug": "papel-de-colores"},
                    {"name": "Papel Fotográfico", "slug": "papel-fotografico"},
                    {"name": "Rollos de Papel para Plotter", "slug": "rollos-papel-plotter"},
                    {"name": "Papel POS", "slug": "papel-pos"},
                    {"name": "Etiquetas POS", "slug": "etiquetas-pos"},
                    {"name": "Tarjetas para Credenciales", "slug": "tarjetas-credenciales"},
                    {"name": "Brazaletes", "slug": "brazaletes"},
                    {"name": "Etiquetas para CD/DVD", "slug": "etiquetas-cd-dvd"},
                    {"name": "Etiquetas Adhesivas", "slug": "etiquetas-adhesivas"},
                    {"name": "Tarjetas de Presentación", "slug": "tarjetas-de-presentacion"},
                ],
            },
            {
                "name": "Refacción para Impresoras",
                "slug": "refaccion-impresoras",
                "children": [
                    {"name": "Tambores", "slug": "tambores"},
                    {"name": "Fusores", "slug": "fusores"},
                    {"name": "Unidades de Transferencia", "slug": "unidades-de-transferencia"},
                    {"name": "Rodillos de Alimentación", "slug": "rodillos-alimentacion"},
                    {"name": "Rodillos de Presión", "slug": "rodillos-presion"},
                    {"name": "Pads Separadores", "slug": "pads-separadores"},
                    {"name": "Reveladores", "slug": "reveladores"},
                    {"name": "Tarjetas para Impresoras", "slug": "tarjetas-impresoras"},
                    {"name": "Enfriamiento para Impresoras", "slug": "enfriamiento-impresoras"},
                    {"name": "Paneles de Control", "slug": "paneles-de-control"},
                ],
            },
            {
                "name": "Accesorios de Impresión",
                "slug": "accesorios-impresion",
                "children": [
                    {"name": "Memorias para Impresoras", "slug": "memorias-impresoras"},
                    {"name": "Kits de Mantenimiento", "slug": "kits-mantenimiento"},
                    {"name": "Bandejas y Alimentadores", "slug": "bandejas-alimentadores"},
                    {"name": "Gabinetes y Soportes", "slug": "gabinetes-soportes"},
                    {"name": "Contenedores de Desperdicio", "slug": "contenedores-desperdicio"},
                    {"name": "Adaptadores de Red para Impresoras", "slug": "adaptadores-red-impresoras"},
                    {"name": "Cargadores para Impresoras", "slug": "cargadores-impresoras"},
                    {"name": "Limpieza para Impresoras", "slug": "limpieza-impresoras"},
                    {"name": "Cables para Impresoras", "slug": "cables-impresoras"},
                    {"name": "Accesorios para Impresión 3D", "slug": "accesorios-impresion-3d-extra"},
                    {"name": "Software para Impresoras", "slug": "software-impresoras"},
                    {"name": "Módulos Multifunción", "slug": "modulos-multifuncion"},
                ],
            },
        ],
    },
    {
        "name": "Punto de Venta (POS)",
        "slug": "punto-de-venta-pos",
        "children": [
            {"name": "Sistemas POS", "slug": "sistemas-pos", "children": []},
            {"name": "Monitores POS", "slug": "monitores-pos", "children": []},
            {"name": "Impresoras de Tickets", "slug": "impresoras-de-tickets-pos", "children": []},
            {"name": "Impresoras Móviles", "slug": "impresoras-moviles-pos", "children": []},
            {"name": "Impresoras de Etiquetas", "slug": "impresoras-de-etiquetas-pos", "children": []},
            {
                "name": "Lectores y Terminales",
                "slug": "lectores-y-terminales",
                "children": [
                    {"name": "Lectores de Código de Barras", "slug": "lectores-codigo-barras"},
                    {"name": "Lectores de Banda Magnética", "slug": "lectores-banda-magnetica"},
                    {"name": "Lectores de Mostrador", "slug": "lectores-mostrador"},
                    {"name": "Terminales Portátiles", "slug": "terminales-portatiles-pos"},
                ],
            },
            {
                "name": "Accesorios",
                "slug": "accesorios-pos",
                "children": [
                    {"name": "Fuentes de Alimentación", "slug": "fuentes-alimentacion-pos"},
                    {"name": "Bases y Montajes", "slug": "bases-montajes-pos"},
                    {"name": "Cables", "slug": "cables-pos"},
                    {"name": "Fundas y Protectores POS", "slug": "fundas-protectores-pos"},
                ],
            },
            {"name": "Cajones de dinero", "slug": "cajones-de-dinero", "children": []},
            {"name": "Pantallas POS Pole", "slug": "pantallas-pos-pole", "children": []},
            {"name": "Teclados POS", "slug": "teclados-pos", "children": []},
        ],
    },
    {
        "name": "Seguridad y Vigilancia",
        "slug": "seguridad-y-vigilancia",
        "children": [
            {
                "name": "Cámaras y Sistemas de Vigilancia",
                "slug": "camaras-y-sistemas-de-vigilancia",
                "children": [
                    {"name": "Kits de Vigilancia", "slug": "kits-de-vigilancia"},
                    {"name": "Cámaras de Seguridad CCTV", "slug": "camaras-seguridad-cctv"},
                    {"name": "Cámaras de Seguridad IP", "slug": "camaras-seguridad-ip"},
                    {"name": "Seguridad para Bebés", "slug": "seguridad-para-bebes"},
                    {"name": "Cámaras Ocultas", "slug": "camaras-ocultas"},
                    {"name": "Cámaras Térmicas", "slug": "camaras-termicas"},
                    {"name": "Grabadoras de Video Digital (DVR)", "slug": "grabadoras-video-dvr"},
                    {"name": "Grabadoras de Video en Red (NVR)", "slug": "grabadoras-video-nvr"},
                    {"name": "Energía para Cámaras y Grabadoras", "slug": "energia-camaras-grabadoras"},
                    {"name": "Accesorios para Videovigilancia", "slug": "accesorios-videovigilancia"},
                    {"name": "Discos Duros para Videovigilancia", "slug": "hdd-videovigilancia"},
                    {"name": "Monitores CCTV", "slug": "monitores-cctv"},
                    {"name": "Carcasas y Gabinetes", "slug": "carcasas-gabinetes"},
                    {"name": "Brazos y Soportes", "slug": "brazos-soportes"},
                    {"name": "Cajas de Conexiones", "slug": "cajas-conexiones"},
                    {"name": "Objetivos Varifocales", "slug": "objetivos-varifocales"},
                    {"name": "Burbujas Humeadas", "slug": "burbujas-humeadas"},
                    {"name": "Tarjetas para Captura de Vídeo", "slug": "tarjetas-captura-video"},
                    {"name": "Servidores de Video IP", "slug": "servidores-video-ip"},
                    {"name": "Micrófonos Profesionales", "slug": "microfonos-profesionales"},
                    {"name": "Controles para Videovigilancia", "slug": "controles-videovigilancia"},
                    {"name": "Iluminadores IR", "slug": "iluminadores-ir"},
                    {"name": "Accesorios para DVR Móviles", "slug": "accesorios-dvr-moviles"},
                    {"name": "Transceptores y Receptores", "slug": "transceptores-receptores"},
                    {"name": "Cables para Videovigilancia", "slug": "cables-videovigilancia"},
                    {"name": "Cables Coaxiales", "slug": "cables-coaxiales"},
                    {"name": "Conectores Coaxiales", "slug": "conectores-coaxiales"},
                    {"name": "Cables y Adaptadores", "slug": "cables-adaptadores-vigilancia"},
                    {"name": "Videowalls", "slug": "videowalls"},
                    {"name": "Software para Seguridad y Vigilancia", "slug": "software-seguridad-vigilancia"},
                ],
            },
            {
                "name": "Body Cams",
                "slug": "body-cams",
                "children": [
                    {"name": "Body Cams", "slug": "body-cams-listado"},
                    {"name": "Accesorios para Body Cams", "slug": "accesorios-body-cams"},
                ],
            },
            {
                "name": "Sistemas de Alarma",
                "slug": "sistemas-de-alarma",
                "children": [
                    {"name": "Kits de Alarma", "slug": "kits-de-alarma"},
                    {"name": "Paneles de Control", "slug": "paneles-control"},
                    {"name": "Sistemas de Alarma Contra Incendios", "slug": "sistemas-alarma-incendios"},
                    {"name": "Aplicaciones Especiales", "slug": "alarmas-aplicaciones-especiales"},
                    {"name": "Paneles de Control para Alarmas de Incendio", "slug": "paneles-control-incendio"},
                    {"name": "Montajes y Cubiertas", "slug": "montajes-cubiertas"},
                    {"name": "Estaciones Manuales de Emergencia", "slug": "estaciones-manuales-emergencia"},
                    {
                        "name": "Detectores y Sensores",
                        "slug": "detectores-sensores",
                        "children": [
                            {"name": "Sensores de Movimiento", "slug": "sensores-movimiento"},
                            {"name": "Detectores de Rotura de Vidrios", "slug": "detectores-rotura-vidrios"},
                            {"name": "Detectores de Gas y Humo", "slug": "detectores-gas-humo"},
                            {"name": "Detectores Fotoeléctricos", "slug": "detectores-fotoelectricos"},
                            {"name": "Detectores de Temperatura", "slug": "detectores-temperatura"},
                            {"name": "Sensores de Humedad", "slug": "sensores-humedad"},
                            {"name": "Detectores de Metal", "slug": "detectores-metal"},
                            {"name": "Unidades Magnéticas", "slug": "unidades-magneticas"},
                            {"name": "Soportes y Montajes para Detectores", "slug": "soportes-montajes-detectores"},
                        ],
                    },
                    {
                        "name": "Cercas Eléctricas",
                        "slug": "cercas-electricas",
                        "children": [
                            {"name": "Aisladores", "slug": "aisladores"},
                            {"name": "Energizadores", "slug": "energizadores"},
                            {"name": "Postes", "slug": "postes"},
                            {"name": "Accesorios para Cercas Eléctricas", "slug": "accesorios-cercas-electricas"},
                        ],
                    },
                    {
                        "name": "Accesorios para Alarmas",
                        "slug": "accesorios-alarmas",
                        "children": [
                            {"name": "Sirenas y Bocinas", "slug": "sirenas-bocinas"},
                            {"name": "Estrobos y Luces Giratorias", "slug": "estrobos-luces-giratorias"},
                            {"name": "Luces Vehiculares", "slug": "luces-vehiculares"},
                            {"name": "Luces Perimetrales", "slug": "luces-perimetrales"},
                            {"name": "Teclados y Controles Remoto", "slug": "teclados-controles-remoto"},
                            {"name": "Botones de Pánico", "slug": "botones-panico"},
                            {"name": "Transmisores por Radio", "slug": "transmisores-radio"},
                            {"name": "Tampers", "slug": "tampers"},
                            {"name": "Tarjetas y Módulos", "slug": "tarjetas-modulos"},
                            {"name": "Accesorios para Luces Vehiculares", "slug": "accesorios-luces-vehiculares"},
                            {"name": "Energía para Sistemas de Alarmas", "slug": "energia-sistemas-alarmas"},
                        ],
                    },
                ],
            },
            {
                "name": "Control de Acceso",
                "slug": "control-de-acceso",
                "children": [
                    {"name": "Videoporteros e Interfones", "slug": "videoporteros-interfones"},
                    {"name": "Videoporteros", "slug": "videoporteros"},
                    {"name": "Interfones", "slug": "interfones"},
                    {"name": "Frentes de Calle", "slug": "frentes-calle"},
                    {"name": "Control de Acceso con Tarjeta", "slug": "control-acceso-tarjeta"},
                    {"name": "Control de Acceso y Asistencia Biométrico", "slug": "control-biometrico"},
                    {"name": "Relojes Checadores", "slug": "relojes-checadores"},
                    {"name": "Lectores de Huella Digital", "slug": "lectores-huella-digital"},
                    {"name": "Paneles Control de Acceso", "slug": "paneles-control-acceso"},
                    {"name": "Paneles Controladores", "slug": "paneles-controladores"},
                    {"name": "Accesorios para Paneles Controladores", "slug": "accesorios-paneles-controladores"},
                    {"name": "Cerraduras y Cerrojos para Control de Acceso", "slug": "cerraduras-control-acceso"},
                    {"name": "Tarjetas y Tags de Acceso", "slug": "tarjetas-tags-acceso"},
                    {"name": "Kits de Instalación", "slug": "kits-instalacion"},
                    {"name": "Botones de Salida", "slug": "botones-salida"},
                    {"name": "Accesorios para Videoporteros", "slug": "accesorios-videoporteros"},
                    {
                        "name": "Acceso Vehicular",
                        "slug": "acceso-vehicular",
                        "children": [
                            {"name": "Control de Acceso Vehicular", "slug": "control-acceso-vehicular"},
                            {"name": "Barreras Vehiculares", "slug": "barreras-vehiculares"},
                            {"name": "Accesorios para Barreras Vehiculares", "slug": "accesorios-barreras-vehiculares"},
                            {"name": "Puertas Abatibles y Corredizas", "slug": "puertas-abatibles-corredizas"},
                            {"name": "Picos Poncha Llantas", "slug": "picos-poncha-llantas"},
                            {"name": "Topes y Reductores de Velocidad", "slug": "topes-reductores-velocidad"},
                            {"name": "Semáforos y Señalización", "slug": "semaforos-senalizacion"},
                            {"name": "Puertas de Cortesía y Torniquetes", "slug": "puertas-cortesia-torniquetes"},
                        ],
                    },
                ],
            },
            {
                "name": "Sistemas de Emergencia",
                "slug": "sistemas-de-emergencia",
                "children": [
                    {"name": "Puertas de Emergencia", "slug": "puertas-emergencia"},
                    {"name": "Barras para Puertas de Emergencia", "slug": "barras-puertas-emergencia"},
                    {"name": "Accesorios para Puertas de Emergencia", "slug": "accesorios-puertas-emergencia"},
                    {"name": "Señales de Emergencia", "slug": "senales-emergencia"},
                    {"name": "Tarjetas de Relevador", "slug": "tarjetas-relevador"},
                ],
            },
            {
                "name": "Protección de Mercancía",
                "slug": "proteccion-mercancia",
                "children": [
                    {"name": "Tags para Ropa", "slug": "tags-ropa"},
                    {"name": "Antenas para Protección", "slug": "antenas-proteccion"},
                ],
            },
            {"name": "Cierrapuertas", "slug": "cierrapuertas", "children": []},
            {"name": "Control de Recorridos", "slug": "control-de-recorridos", "children": []},
        ],
    },
    {
        "name": "Software y Servicios",
        "slug": "software-y-servicios",
        "children": [
            {"name": "Sistemas Operativos", "slug": "sistemas-operativos", "children": []},
            {"name": "Sistemas Operativos para Servidores", "slug": "sistemas-operativos-servidores", "children": []},
            {"name": "Microsoft Office", "slug": "microsoft-office", "children": []},
            {"name": "Microsoft 365", "slug": "microsoft-365", "children": []},
            {"name": "Antivirus", "slug": "antivirus", "children": []},
            {
                "name": "Videojuegos",
                "slug": "videojuegos",
                "children": [
                    {"name": "Juegos Xbox One", "slug": "juegos-xbox-one"},
                    {"name": "Juegos Xbox 360", "slug": "juegos-xbox-360"},
                    {"name": "Complementos para Videojuegos", "slug": "complementos-videojuegos"},
                ],
            },
            {"name": "Respaldos y Utilidades", "slug": "respaldos-y-utilidades", "children": []},
            {
                "name": "Licencias y Garantías",
                "slug": "licencias-y-garantias",
                "children": [
                    {"name": "Licencias de Aplicación de Software", "slug": "licencias-aplicacion-software"},
                    {"name": "Garantías", "slug": "garantias"},
                ],
            },
        ],
    },
    {
        "name": "Otros",
        "slug": "otros",
        "children": [
            {"name": "productos varios", "slug": "productos-varios"},
        ],
    },
]
