# Generated by Django 5.2.4 on 2025-10-14 22:13

from django.conf import settings
from django.db import migrations, models


def link_items_to_carts(apps, schema_editor):
    Cart = apps.get_model('carrito', 'Cart')
    CartItem = apps.get_model('carrito', 'CartItem')
    CartReservation = apps.get_model('carrito', 'CartReservation')

    # Ensure carts exist for users with items or reservations
    user_ids = set(
        CartItem.objects.exclude(user_id=None).values_list('user_id', flat=True)
    ) | set(
        CartReservation.objects.exclude(user_id=None).values_list('user_id', flat=True)
    )
    for user_id in user_ids:
        Cart.objects.get_or_create(user_id=user_id)

    # Attach items to their corresponding carts
    for item in CartItem.objects.all():
        if item.user_id:
            cart, _ = Cart.objects.get_or_create(user_id=item.user_id)
            item.cart_id = cart.id
            item.save(update_fields=['cart'])
        else:
            cart = Cart.objects.create()
            item.cart_id = cart.id
            item.save(update_fields=['cart'])

    # Attach reservations to carts
    for reserva in CartReservation.objects.all():
        if reserva.user_id:
            cart, _ = Cart.objects.get_or_create(user_id=reserva.user_id)
            reserva.cart_id = cart.id
            reserva.save(update_fields=['cart'])


def unlink_items_from_carts(apps, schema_editor):
    CartItem = apps.get_model('carrito', 'CartItem')
    CartReservation = apps.get_model('carrito', 'CartReservation')
    CartItem.objects.update(cart_id=None)
    CartReservation.objects.update(cart_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0002_cartreservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=models.CASCADE,
                related_name="items",
                to="carrito.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartreservation",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=models.CASCADE,
                related_name="reservation",
                to="carrito.cart",
            ),
        ),
        migrations.RunPython(link_items_to_carts, unlink_items_from_carts),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="items",
                to="carrito.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartreservation",
            name="cart",
            field=models.OneToOneField(
                on_delete=models.CASCADE,
                related_name="reservation",
                to="carrito.cart",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "producto")},
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cartreservation",
            name="user",
        ),
    ]
