# Generated by Django 5.2.4 on 2025-11-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_supplierproduct_available_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='The discounted price for the offer.', max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='The price of the product before the discount was applied.', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='The date and time when the offer starts.')),
                ('end_date', models.DateTimeField(help_text='The date and time when the offer ends.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the offer is currently active.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_offers', to='suppliers.supplierproduct')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
