# Generated by Django 5.2.4 on 2025-11-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_offers_enabled', models.BooleanField(default=False, help_text='Enable or disable the automatic creation of daily offers.')),
            ],
        ),
    ]
