# Generated by Django 5.2.4 on 2026-03-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo')], default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de compra requerido. Vacío = sin mínimo', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-id'],
            },
        ),
    ]
