# Generated by Django 5.2.4 on 2025-08-02 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("nombre_empresa", models.CharField(blank=True, max_length=150)),
                ("calle", models.CharField(max_length=150)),
                ("numero_exterior", models.CharField(max_length=50)),
                ("numero_interior", models.CharField(blank=True, max_length=50)),
                ("colonia", models.CharField(max_length=150)),
                ("ciudad", models.CharField(max_length=150)),
                ("pais", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=20)),
                ("referencias", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direcciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferencia directa"),
                            ("tarjeta", "Tarjeta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "direccion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="pedidos.direccion",
                    ),
                ),
                (
                    "metodo_envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedidos.metodoenvio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('pedidos', 'MetodoEnvio').objects.bulk_create([
                apps.get_model('pedidos', 'MetodoEnvio')(nombre='Estafeta', costo=299),
                apps.get_model('pedidos', 'MetodoEnvio')(nombre='FedEx', costo=395),
            ])
        ),
    ]
