# Generated by Django 5.2.4 on 2025-08-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedidos",
            "0002_pedido_costo_envio_pedido_datos_pago_pedido_subtotal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pagado", "Pagado"),
                    ("confirmado", "Confirmado"),
                    ("enviado", "Enviado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="stock_restaurado",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PedidoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="pedidos.pedido",
                    ),
                ),
            ],
        ),
    ]
