# Generated by Django 5.2.4 on 2025-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_estado_pedido_stock_restaurado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metodoenvio",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
