# Generated by Django 5.2.4 on 2025-08-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_metodoenvio_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccion",
            name="predeterminada",
            field=models.BooleanField(default=False),
        ),
    ]
