# Generated by Django 5.2.4 on 2025-08-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_direccion_predeterminada"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="papelera",
            field=models.BooleanField(default=False),
        ),
    ]
