# Generated by Django 5.2.4 on 2025-10-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0003_migrate_to_session_carts"),
        ("pedidos", "0006_pedido_eliminado_en_pedido_papelera"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="carrito.cart",
            ),
        ),
    ]
