# Generated by Django 5.2.4 on 2025-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodoenvio',
            options={'ordering': ['id']},
        ),
    ]
