# Generated by Django 5.2.4 on 2025-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_metodoenvio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='datos_pago',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
