# Generated by Django 5.2.4 on 2025-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='datos_pago',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
