# Generated by Django 5.2.4 on 2026-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_datos_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia directa'), ('tarjeta', 'Tarjeta'), ('mercadopago', 'Mercado Pago')], max_length=20),
        ),
    ]
