# Generated by Django 5.2.4 on 2026-03-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_numero_guia'),
        ('promotions', '0003_cupones_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='promotions.cupon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
