# Generated by Django 5.2.4 on 2025-07-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_atributo_categoria_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True),
        ),
    ]
