# Generated by Django 5.2.4 on 2025-07-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_descripcion_larga'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='miniatura',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='productos/miniaturas/'),
        ),
    ]
