# Generated by Django 5.2.4 on 2025-07-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_miniatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
    ]
