# Generated by Django 5.2.4 on 2025-08-06 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_remove_producto_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="productos.categoria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
