# Generated by Django 5.2.4 on 2025-10-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_producto_categorias_producto_fecha_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="category_ai_conf_main",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="category_ai_conf_sub",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="category_ai_main",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="category_ai_sub",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
