# Generated by Django 5.2.4 on 2025-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_categoria_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('slug', 'parent')},
        ),
    ]
