# Generated by Django 5.2.4 on 2025-10-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_categoria_slug_alter_categoria_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
