# Generated by Django 5.2.4 on 2025-10-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo',
            options={'ordering': ['nombre', 'id']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre', 'id']},
        ),
        migrations.AlterModelOptions(
            name='valoratributo',
            options={'ordering': ['valor', 'id']},
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.atributo'),
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='valor',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='valoratributo',
            constraint=models.UniqueConstraint(fields=('atributo', 'valor'), name='uniq_atributo_valor'),
        ),
    ]
