# Generated by Django 5.2.4 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_atributo_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_clasificacion_ai',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última clasificación por IA.', null=True),
        ),
    ]
