# Generated by Django 5.2.4 on 2026-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_producto_fecha_clasificacion_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], db_index=True, default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_inventario',
            field=models.CharField(choices=[('en_existencia', 'En existencia'), ('agotado', 'Agotado')], db_index=True, default='en_existencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='visibilidad',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
