# Generated by Django 5.0.4 on 2026-01-09 04:00

from django.db import migrations

def migrate_categoria_to_categorias(apps, schema_editor):
    """
    Migrates the data from the old single 'categoria' ForeignKey
    to the new 'categorias' ManyToManyField.
    """
    Producto = apps.get_model('productos', 'Producto')
    for producto in Producto.objects.filter(categoria__isnull=False).iterator():
        producto.categorias.add(producto.categoria)

def do_nothing(apps, schema_editor):
    """
    This function is used for the reverse operation, which does nothing.
    If we were to reverse this migration, we wouldn't want to lose the
    data in the 'categorias' field.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_producto_fecha_clasificacion_ai'),
    ]

    operations = [
        migrations.RunPython(migrate_categoria_to_categorias, reverse_code=do_nothing),
    ]
