# Generated by Django 5.0.4 on 2026-01-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_migrate_categoria_to_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
