# Generated by Django 5.2.4 on 2026-03-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_productclassificationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('imagen', models.ImageField(upload_to='home_slider/')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
