# Generated by Django 5.2.4 on 2026-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_homesliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesliderimage',
            name='descripcion_mobile',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homesliderimage',
            name='imagen_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='home_slider/mobile/'),
        ),
        migrations.AddField(
            model_name='homesliderimage',
            name='titulo_mobile',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
