# Generated by Django 5.2.4 on 2026-03-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_homesliderimage_descripcion_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesliderimage',
            name='titulo_color',
            field=models.CharField(blank=True, default='#ea580c', max_length=7),
        ),
    ]
