# Generated by Django 5.2.4 on 2026-03-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_promobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], db_index=True, default='manual', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('prioridad', models.PositiveIntegerField(default=0, help_text='Menor número = más prioritario. Solo aplica para tipo manual.')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde la que el destacado es válido. Null = siempre.', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de vencimiento opcional. Null = sin vencimiento.', null=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Si está activo, el algoritmo automático no modificará este registro.')),
                ('puntaje_auto', models.FloatField(blank=True, help_text='Puntaje calculado por el algoritmo automático.', null=True)),
                ('motivo', models.CharField(blank=True, choices=[('campana', 'Destacado manual por campaña'), ('ventas', 'Destacado automático por ventas'), ('novedad', 'Destacado automático por novedad'), ('oferta', 'Destacado automático por oferta')], help_text='Razón principal del destacado.', max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destacado', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Productos Destacados',
                'ordering': ['prioridad', '-puntaje_auto', 'id'],
            },
        ),
    ]
