# Generated by Django 5.2.4 on 2025-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_perfil_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("admin", "Administrador"),
                    ("super_admin", "Super Administrador"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
