# Generated by Django 5.2.4 on 2025-09-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0007_producto_categorias_producto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='supermex', max_length=50)),
                ('supplier_sku', models.CharField(max_length=64, unique=True)),
                ('product_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('image_urls', models.JSONField(default=list)),
                ('price_supplier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplierMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='supermex', max_length=50)),
                ('supplier_sku', models.CharField(max_length=64, unique=True)),
                ('auto_hide_when_oos', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='productos.producto')),
            ],
        ),
    ]
