# Generated by Django 5.2.4 on 2025-09-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='available_qty',
            field=models.IntegerField(default=0),
        ),
    ]
