# Generated by Django 5.2.4 on 2026-03-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierproduct_available_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='odoo_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='odoo_template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
